import { api } from './apiClient';

export interface ProfessionCategory {
  id: number;
  slug: string;
  name: string;
  parentId: number | null;
  level: 1 | 2 | 3;
  order: number;
  isActive: boolean;
  createdAt: string;
  updatedAt: string;
  _count?: {
    children: number;
  };
}

export interface ProfessionCategoryDetail extends ProfessionCategory {
  parent: Pick<ProfessionCategory, 'id' | 'slug' | 'name' | 'level'> | null;
  children: ProfessionCategory[];
}

export interface CreateRubroPayload {
  name: string;
  slug?: string;
  order?: number;
  isActive?: boolean;
}

export interface CreateSubrubroPayload {
  name: string;
  slug?: string;
  rubroId: number;
  order?: number;
  isActive?: boolean;
}

export interface CreateProfesionPayload {
  name: string;
  slug?: string;
  subrubroId: number;
  order?: number;
  isActive?: boolean;
}

export type UpdateRubroPayload = Partial<CreateRubroPayload>;
export type UpdateSubrubroPayload = Partial<CreateSubrubroPayload & { rubroId?: number }>;
export type UpdateProfesionPayload = Partial<CreateProfesionPayload & { subrubroId?: number }>;

export interface DeactivateResponse {
  message: string;
}

const BASE_PATH = '/admin/profession-categories';

function buildQuery(params: Record<string, string | number | boolean | undefined>): string {
  const searchParams = new URLSearchParams();
  for (const [key, value] of Object.entries(params)) {
    if (value !== undefined) {
      searchParams.set(key, String(value));
    }
  }
  const query = searchParams.toString();
  return query ? `?${query}` : '';
}

// Rubros
export function getRubros(): Promise<ProfessionCategory[]> {
  return api.get<ProfessionCategory[]>(`${BASE_PATH}/rubros`);
}

export function getRubro(id: number): Promise<ProfessionCategoryDetail> {
  return api.get<ProfessionCategoryDetail>(`${BASE_PATH}/rubros/${id}`);
}

export function createRubro(payload: CreateRubroPayload): Promise<ProfessionCategory> {
  return api.post<ProfessionCategory>(`${BASE_PATH}/rubros`, payload);
}

export function updateRubro(id: number, payload: UpdateRubroPayload): Promise<ProfessionCategory> {
  return api.patch<ProfessionCategory>(`${BASE_PATH}/rubros/${id}`, payload);
}

export function deleteRubro(id: number): Promise<DeactivateResponse> {
  return api.del<DeactivateResponse>(`${BASE_PATH}/rubros/${id}`);
}

// Subrubros
export function getSubrubros(rubroId?: number): Promise<ProfessionCategory[]> {
  const query = buildQuery({ rubroId });
  return api.get<ProfessionCategory[]>(`${BASE_PATH}/subrubros${query}`);
}

export function getSubrubro(id: number): Promise<ProfessionCategoryDetail> {
  return api.get<ProfessionCategoryDetail>(`${BASE_PATH}/subrubros/${id}`);
}

export function createSubrubro(payload: CreateSubrubroPayload): Promise<ProfessionCategory> {
  return api.post<ProfessionCategory>(`${BASE_PATH}/subrubros`, payload);
}

export function updateSubrubro(id: number, payload: UpdateSubrubroPayload): Promise<ProfessionCategory> {
  return api.patch<ProfessionCategory>(`${BASE_PATH}/subrubros/${id}`, payload);
}

export function deleteSubrubro(id: number): Promise<DeactivateResponse> {
  return api.del<DeactivateResponse>(`${BASE_PATH}/subrubros/${id}`);
}

// Profesiones
export function getProfesiones(subrubroId?: number): Promise<ProfessionCategory[]> {
  const query = buildQuery({ subrubroId });
  return api.get<ProfessionCategory[]>(`${BASE_PATH}/profesiones${query}`);
}

export function getProfesion(id: number): Promise<ProfessionCategoryDetail> {
  return api.get<ProfessionCategoryDetail>(`${BASE_PATH}/profesiones/${id}`);
}

export function createProfesion(payload: CreateProfesionPayload): Promise<ProfessionCategory> {
  return api.post<ProfessionCategory>(`${BASE_PATH}/profesiones`, payload);
}

export function updateProfesion(id: number, payload: UpdateProfesionPayload): Promise<ProfessionCategory> {
  return api.patch<ProfessionCategory>(`${BASE_PATH}/profesiones/${id}`, payload);
}

export function deleteProfesion(id: number): Promise<DeactivateResponse> {
  return api.del<DeactivateResponse>(`${BASE_PATH}/profesiones/${id}`);
}

// Traceability: generated by Programmer at 2026-05-20 18:02:23
